// DO NOT EDIT. This file is generated by shape_compile.

void
cui_draw_fill_shape(CuiGraphicsContext *ctx, float x, float y, CuiShapeType shape_type, float scale, CuiColor color)
{
    float draw_x = x;
    float draw_y = y;

    float bitmap_x = floorf(draw_x);
    float bitmap_y = floorf(draw_y);

    float offset_x = draw_x - bitmap_x;
    float offset_y = bitmap_y - draw_y;

    offset_x = 0.125f * roundf(offset_x * 8.0f);
    offset_y = 0.125f * roundf(offset_y * 8.0f);

    CuiRect uv;

    if (!_cui_glyph_cache_find(ctx->glyph_cache, 0, shape_type, scale, offset_x, offset_y, &uv))
    {
        CuiTemporaryMemory temp_memory = cui_begin_temporary_memory(ctx->temporary_memory);

        switch (shape_type)
        {
            case CUI_SHAPE_ROUNDED_CORNER:           { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_INVERTED_ROUNDED_CORNER:  { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_SHADOW_CORNER:            { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_SHADOW_HORIZONTAL:        { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_SHADOW_VERTICAL:          { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_WINDOWS_MINIMIZE:         { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_WINDOWS_MAXIMIZE:         { CuiAssert(!"unsupported"); } break;
            case CUI_SHAPE_WINDOWS_CLOSE:            { CuiAssert(!"unsupported"); } break;

            case CUI_SHAPE_CHECKBOX_OUTER_16:
            {
                int32_t width  = (int32_t) ceilf(scale * 16.0f);
                int32_t height = (int32_t) ceilf(scale * 16.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 3.000000f, scale * 1.000000f);
                cui_path_line_to(&path, scale * 13.000000f, scale * 1.000000f);
                cui_path_cubic_curve_to(&path, scale * 14.108001f, scale * 1.000000f, scale * 15.000000f, scale * 1.892000f, scale * 15.000000f, scale * 3.000000f);
                cui_path_line_to(&path, scale * 15.000000f, scale * 13.000000f);
                cui_path_cubic_curve_to(&path, scale * 15.000000f, scale * 14.108001f, scale * 14.108001f, scale * 15.000000f, scale * 13.000000f, scale * 15.000000f);
                cui_path_line_to(&path, scale * 3.000000f, scale * 15.000000f);
                cui_path_cubic_curve_to(&path, scale * 1.892000f, scale * 15.000000f, scale * 1.000000f, scale * 14.108001f, scale * 1.000000f, scale * 13.000000f);
                cui_path_line_to(&path, scale * 1.000000f, scale * 3.000000f);
                cui_path_cubic_curve_to(&path, scale * 1.000000f, scale * 1.892000f, scale * 1.892000f, scale * 1.000000f, scale * 3.000000f, scale * 1.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_CHECKBOX_INNER_16:
            {
                int32_t width  = (int32_t) ceilf(scale * 16.0f);
                int32_t height = (int32_t) ceilf(scale * 16.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 3.000000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 13.000000f, scale * 2.000000f);
                cui_path_cubic_curve_to(&path, scale * 13.554000f, scale * 2.000000f, scale * 14.000000f, scale * 2.446000f, scale * 14.000000f, scale * 3.000000f);
                cui_path_line_to(&path, scale * 14.000000f, scale * 13.000000f);
                cui_path_cubic_curve_to(&path, scale * 14.000000f, scale * 13.554000f, scale * 13.554000f, scale * 14.000000f, scale * 13.000000f, scale * 14.000000f);
                cui_path_line_to(&path, scale * 3.000000f, scale * 14.000000f);
                cui_path_cubic_curve_to(&path, scale * 2.446000f, scale * 14.000000f, scale * 2.000000f, scale * 13.554000f, scale * 2.000000f, scale * 13.000000f);
                cui_path_line_to(&path, scale * 2.000000f, scale * 3.000000f);
                cui_path_cubic_curve_to(&path, scale * 2.000000f, scale * 2.446000f, scale * 2.446000f, scale * 2.000000f, scale * 3.000000f, scale * 2.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_CHECKMARK_16:
            {
                int32_t width  = (int32_t) ceilf(scale * 16.0f);
                int32_t height = (int32_t) ceilf(scale * 16.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 11.910155f, scale * 4.003906f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 11.232421f, scale * 4.359375f);
                cui_path_line_to(&path, scale * 6.933594f, scale * 9.519530f);
                cui_path_line_to(&path, scale * 4.707031f, scale * 7.292968f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 3.292969f, scale * 7.292968f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 3.292969f, scale * 8.707030f);
                cui_path_line_to(&path, scale * 6.292968f, scale * 11.707030f);
                cui_path_arc_to(&path, scale * 1.000100f, scale * 1.000100f, 0.000000f, false, false, scale * 7.767578f, scale * 11.640625f);
                cui_path_line_to(&path, scale * 12.767577f, scale * 5.640625f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 12.640625f, scale * 4.232422f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 11.910155f, scale * 4.003906f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_ANGLE_UP_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 5.292951f, scale * 2.292776f);
                cui_path_line_to(&path, scale * 0.292825f, scale * 7.292777f);
                cui_path_arc_to(&path, scale * 1.000025f, scale * 1.000000f, 0.000000f, false, false, scale * 0.292825f, scale * 8.706838f);
                cui_path_arc_to(&path, scale * 1.000025f, scale * 1.000000f, 0.000000f, false, false, scale * 1.706924f, scale * 8.706838f);
                cui_path_line_to(&path, scale * 6.000000f, scale * 4.413870f);
                cui_path_line_to(&path, scale * 10.293077f, scale * 8.706838f);
                cui_path_arc_to(&path, scale * 1.000025f, scale * 1.000000f, 0.000000f, false, false, scale * 11.707174f, scale * 8.706838f);
                cui_path_arc_to(&path, scale * 1.000025f, scale * 1.000000f, 0.000000f, false, false, scale * 11.707174f, scale * 7.292777f);
                cui_path_line_to(&path, scale * 6.707049f, scale * 2.292776f);
                cui_path_arc_to(&path, scale * 1.000125f, scale * 1.000100f, 0.000000f, false, false, scale * 5.292951f, scale * 2.292776f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_ANGLE_RIGHT_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 9.706880f, scale * 6.706880f);
                cui_path_line_to(&path, scale * 4.706881f, scale * 11.706880f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 3.292818f, scale * 11.706880f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 3.292818f, scale * 10.292816f);
                cui_path_line_to(&path, scale * 7.585787f, scale * 5.999849f);
                cui_path_line_to(&path, scale * 3.292818f, scale * 1.706880f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 3.292818f, scale * 0.292818f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 4.706881f, scale * 0.292818f);
                cui_path_line_to(&path, scale * 9.706880f, scale * 5.292818f);
                cui_path_arc_to(&path, scale * 1.000100f, scale * 1.000100f, 0.000000f, false, true, scale * 9.706880f, scale * 6.706880f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_ANGLE_DOWN_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 5.292818f, scale * 9.706880f);
                cui_path_line_to(&path, scale * 0.292818f, scale * 4.706881f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 0.292818f, scale * 3.292818f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 1.706881f, scale * 3.292818f);
                cui_path_line_to(&path, scale * 5.999849f, scale * 7.585787f);
                cui_path_line_to(&path, scale * 10.292817f, scale * 3.292818f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 11.706880f, scale * 3.292818f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 11.706880f, scale * 4.706881f);
                cui_path_line_to(&path, scale * 6.706880f, scale * 9.706880f);
                cui_path_arc_to(&path, scale * 1.000100f, scale * 1.000100f, 0.000000f, false, true, scale * 5.292818f, scale * 9.706880f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_ANGLE_LEFT_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 2.292776f, scale * 6.706880f);
                cui_path_line_to(&path, scale * 7.292777f, scale * 11.706880f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 8.706838f, scale * 11.706880f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 8.706838f, scale * 10.292816f);
                cui_path_line_to(&path, scale * 4.413870f, scale * 5.999849f);
                cui_path_line_to(&path, scale * 8.706838f, scale * 1.706880f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 8.706838f, scale * 0.292818f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 7.292777f, scale * 0.292818f);
                cui_path_line_to(&path, scale * 2.292776f, scale * 5.292818f);
                cui_path_arc_to(&path, scale * 1.000100f, scale * 1.000100f, 0.000000f, false, false, scale * 2.292776f, scale * 6.706880f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_INFO_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 6.000000f, scale * 0.500000f);
                cui_path_cubic_curve_to(&path, scale * 5.171573f, scale * 0.500000f, scale * 4.500000f, scale * 1.171573f, scale * 4.500000f, scale * 2.000000f);
                cui_path_cubic_curve_to(&path, scale * 4.500000f, scale * 2.828427f, scale * 5.171573f, scale * 3.500000f, scale * 6.000000f, scale * 3.500000f);
                cui_path_cubic_curve_to(&path, scale * 6.828427f, scale * 3.500000f, scale * 7.500000f, scale * 2.828427f, scale * 7.500000f, scale * 2.000000f);
                cui_path_cubic_curve_to(&path, scale * 7.500000f, scale * 1.171573f, scale * 6.828427f, scale * 0.500000f, scale * 6.000000f, scale * 0.500000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 3.500000f, scale * 5.000000f);
                cui_path_line_to(&path, scale * 3.500000f, scale * 6.000000f);
                cui_path_cubic_curve_to(&path, scale * 4.190356f, scale * 6.000000f, scale * 4.750000f, scale * 6.126929f, scale * 4.750000f, scale * 6.500000f);
                cui_path_line_to(&path, scale * 4.750000f, scale * 10.500000f);
                cui_path_cubic_curve_to(&path, scale * 4.750000f, scale * 10.860277f, scale * 4.190356f, scale * 11.000000f, scale * 3.500000f, scale * 11.000000f);
                cui_path_line_to(&path, scale * 3.500000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 4.750000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 7.250000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 8.500000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 8.500000f, scale * 11.000000f);
                cui_path_cubic_curve_to(&path, scale * 7.809644f, scale * 11.000000f, scale * 7.250000f, scale * 10.859325f, scale * 7.250000f, scale * 10.500000f);
                cui_path_line_to(&path, scale * 7.250000f, scale * 5.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_EXPAND_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 6.000000f, scale * 0.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 5.000000f, scale * 1.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 6.000000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 10.000000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 10.000000f, scale * 6.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 11.000000f, scale * 7.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 12.000000f, scale * 6.000000f);
                cui_path_line_to(&path, scale * 12.000000f, scale * 1.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 11.000000f, scale * 0.000000f);
                cui_path_line_to(&path, scale * 6.000000f, scale * 0.000000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 1.000000f, scale * 5.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 0.000000f, scale * 6.000000f);
                cui_path_line_to(&path, scale * 0.000000f, scale * 11.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 1.000000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 6.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 7.000000f, scale * 11.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 6.000000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 2.000000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 2.000000f, scale * 6.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 1.000000f, scale * 5.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_SEARCH_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 5.000000f, scale * 0.250000f);
                cui_path_cubic_curve_to(&path, scale * 2.385536f, scale * 0.250000f, scale * 0.250000f, scale * 2.385536f, scale * 0.250000f, scale * 5.000000f);
                cui_path_cubic_curve_to(&path, scale * 0.250000f, scale * 7.614464f, scale * 2.385536f, scale * 9.750000f, scale * 5.000000f, scale * 9.750000f);
                cui_path_cubic_curve_to(&path, scale * 6.037369f, scale * 9.750000f, scale * 6.998166f, scale * 9.412681f, scale * 7.781250f, scale * 8.843750f);
                cui_path_line_to(&path, scale * 10.468750f, scale * 11.531250f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 11.531250f, scale * 11.531250f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 11.531250f, scale * 10.468750f);
                cui_path_line_to(&path, scale * 8.843750f, scale * 7.781250f);
                cui_path_cubic_curve_to(&path, scale * 9.412681f, scale * 6.998166f, scale * 9.750000f, scale * 6.037369f, scale * 9.750000f, scale * 5.000000f);
                cui_path_cubic_curve_to(&path, scale * 9.750000f, scale * 2.385536f, scale * 7.614464f, scale * 0.250000f, scale * 5.000000f, scale * 0.250000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 5.000000f, scale * 1.750000f);
                cui_path_cubic_curve_to(&path, scale * 6.803805f, scale * 1.750000f, scale * 8.250000f, scale * 3.196194f, scale * 8.250000f, scale * 5.000000f);
                cui_path_cubic_curve_to(&path, scale * 8.250000f, scale * 6.803805f, scale * 6.803805f, scale * 8.250000f, scale * 5.000000f, scale * 8.250000f);
                cui_path_cubic_curve_to(&path, scale * 3.196194f, scale * 8.250000f, scale * 1.750000f, scale * 6.803805f, scale * 1.750000f, scale * 5.000000f);
                cui_path_cubic_curve_to(&path, scale * 1.750000f, scale * 3.196194f, scale * 3.196194f, scale * 1.750000f, scale * 5.000000f, scale * 1.750000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_A_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 6.000000f, scale * 1.250000f);
                cui_path_arc_to(&path, scale * 0.750075f, scale * 0.750075f, 0.000000f, false, false, scale * 5.296875f, scale * 1.736328f);
                cui_path_line_to(&path, scale * 2.296875f, scale * 9.736327f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.736328f, scale * 10.703125f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.703125f, scale * 10.263672f);
                cui_path_line_to(&path, scale * 4.271484f, scale * 8.750000f);
                cui_path_line_to(&path, scale * 7.728515f, scale * 8.750000f);
                cui_path_line_to(&path, scale * 8.296874f, scale * 10.263672f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.263672f, scale * 10.703125f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.703125f, scale * 9.736327f);
                cui_path_line_to(&path, scale * 6.703125f, scale * 1.736328f);
                cui_path_arc_to(&path, scale * 0.750075f, scale * 0.750075f, 0.000000f, false, false, scale * 6.000000f, scale * 1.250000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 6.000000f, scale * 4.138672f);
                cui_path_line_to(&path, scale * 7.166015f, scale * 7.250000f);
                cui_path_line_to(&path, scale * 4.833984f, scale * 7.250000f);
                cui_path_line_to(&path, scale * 6.000000f, scale * 4.138672f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_B_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 3.005860f, scale * 1.220703f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.250000f, scale * 1.964844f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.251953f, scale * 1.982422f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.250000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 2.250000f, scale * 6.000000f);
                cui_path_line_to(&path, scale * 2.250000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.251953f, scale * 10.017577f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.250000f, scale * 10.035155f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.005860f, scale * 10.779296f);
                cui_path_line_to(&path, scale * 7.000000f, scale * 10.750000f);
                cui_path_cubic_curve_to(&path, scale * 8.509894f, scale * 10.750000f, scale * 9.750000f, scale * 9.509894f, scale * 9.750000f, scale * 8.000000f);
                cui_path_cubic_curve_to(&path, scale * 9.750000f, scale * 7.215074f, scale * 9.414812f, scale * 6.502784f, scale * 8.880858f, scale * 6.000000f);
                cui_path_cubic_curve_to(&path, scale * 9.414812f, scale * 5.497216f, scale * 9.750000f, scale * 4.784926f, scale * 9.750000f, scale * 4.000000f);
                cui_path_cubic_curve_to(&path, scale * 9.750000f, scale * 2.490105f, scale * 8.509894f, scale * 1.250000f, scale * 7.000000f, scale * 1.250000f);
                cui_path_line_to(&path, scale * 3.005860f, scale * 1.220703f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 3.750000f, scale * 2.726562f);
                cui_path_line_to(&path, scale * 6.994141f, scale * 2.750000f);
                cui_path_arc_to(&path, scale * 0.750075f, scale * 0.750075f, 0.000000f, false, false, scale * 7.000000f, scale * 2.750000f);
                cui_path_cubic_curve_to(&path, scale * 7.699237f, scale * 2.750000f, scale * 8.250000f, scale * 3.300763f, scale * 8.250000f, scale * 4.000000f);
                cui_path_cubic_curve_to(&path, scale * 8.250000f, scale * 4.699237f, scale * 7.699237f, scale * 5.250000f, scale * 7.000000f, scale * 5.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 5.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 2.726562f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 3.750000f, scale * 6.750000f);
                cui_path_line_to(&path, scale * 7.000000f, scale * 6.750000f);
                cui_path_cubic_curve_to(&path, scale * 7.699237f, scale * 6.750000f, scale * 8.250000f, scale * 7.300763f, scale * 8.250000f, scale * 8.000000f);
                cui_path_cubic_curve_to(&path, scale * 8.250000f, scale * 8.699238f, scale * 7.699237f, scale * 9.250000f, scale * 7.000000f, scale * 9.250000f);
                cui_path_arc_to(&path, scale * 0.750075f, scale * 0.750075f, 0.000000f, false, false, scale * 6.994141f, scale * 9.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 9.273437f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 6.750000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_G_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);


                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_H_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 3.000000f, scale * 1.250000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.250000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 2.250000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.000000f, scale * 10.750000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.750000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 6.750000f);
                cui_path_line_to(&path, scale * 8.250000f, scale * 6.750000f);
                cui_path_line_to(&path, scale * 8.250000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.000000f, scale * 10.750000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.750000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 9.750000f, scale * 2.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.000000f, scale * 1.250000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 8.250000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 8.250000f, scale * 5.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 5.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 2.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.000000f, scale * 1.250000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_L_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 4.000000f, scale * 1.250000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.250000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 3.250000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.750075f, scale * 0.750075f, 0.000000f, false, false, scale * 4.000000f, scale * 10.750000f);
                cui_path_line_to(&path, scale * 8.000000f, scale * 10.750000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 8.750000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 8.000000f, scale * 9.250000f);
                cui_path_line_to(&path, scale * 4.750000f, scale * 9.250000f);
                cui_path_line_to(&path, scale * 4.750000f, scale * 2.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 4.000000f, scale * 1.250000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_R_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 3.000000f, scale * 1.250000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.250000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 2.250000f, scale * 6.000000f);
                cui_path_line_to(&path, scale * 2.250000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.000000f, scale * 10.750000f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 3.750000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 6.750000f);
                cui_path_line_to(&path, scale * 6.537110f, scale * 6.750000f);
                cui_path_line_to(&path, scale * 8.330077f, scale * 10.335938f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.335938f, scale * 10.669923f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.669923f, scale * 9.664063f);
                cui_path_line_to(&path, scale * 8.097655f, scale * 6.519531f);
                cui_path_cubic_curve_to(&path, scale * 9.066838f, scale * 6.092681f, scale * 9.750000f, scale * 5.120387f, scale * 9.750000f, scale * 4.000000f);
                cui_path_cubic_curve_to(&path, scale * 9.750000f, scale * 2.490103f, scale * 8.509896f, scale * 1.250000f, scale * 7.000000f, scale * 1.250000f);
                cui_path_line_to(&path, scale * 3.000000f, scale * 1.250000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 3.750000f, scale * 2.750000f);
                cui_path_line_to(&path, scale * 7.000000f, scale * 2.750000f);
                cui_path_cubic_curve_to(&path, scale * 7.699238f, scale * 2.750000f, scale * 8.250000f, scale * 3.300762f, scale * 8.250000f, scale * 4.000000f);
                cui_path_cubic_curve_to(&path, scale * 8.250000f, scale * 4.699238f, scale * 7.699238f, scale * 5.250000f, scale * 7.000000f, scale * 5.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 5.250000f);
                cui_path_line_to(&path, scale * 3.750000f, scale * 2.750000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_S_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);


                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_UPPERCASE_V_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 2.736328f, scale * 1.296875f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.296875f, scale * 2.263672f);
                cui_path_line_to(&path, scale * 5.296875f, scale * 10.263672f);
                cui_path_arc_to(&path, scale * 0.750075f, scale * 0.750075f, 0.000000f, false, false, scale * 6.703125f, scale * 10.263672f);
                cui_path_line_to(&path, scale * 9.703125f, scale * 2.263672f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 9.263672f, scale * 1.296875f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 8.296874f, scale * 1.736328f);
                cui_path_line_to(&path, scale * 6.000000f, scale * 7.861328f);
                cui_path_line_to(&path, scale * 3.703125f, scale * 1.736328f);
                cui_path_arc_to(&path, scale * 0.750000f, scale * 0.750000f, 0.000000f, false, false, scale * 2.736328f, scale * 1.296875f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_PLUS_12:
            {
                int32_t width  = (int32_t) ceilf(scale * 12.0f);
                int32_t height = (int32_t) ceilf(scale * 12.0f);

                uv = _cui_glyph_cache_allocate_texture(ctx->glyph_cache, width, height, ctx->command_buffer);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->glyph_cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->glyph_cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, ctx->temporary_memory);

                cui_path_move_to(&path, scale * 6.000000f, scale * 1.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 5.000000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 5.000000f, scale * 5.000000f);
                cui_path_line_to(&path, scale * 2.000000f, scale * 5.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 1.000000f, scale * 6.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 2.000000f, scale * 7.000000f);
                cui_path_line_to(&path, scale * 5.000000f, scale * 7.000000f);
                cui_path_line_to(&path, scale * 5.000000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 6.000000f, scale * 11.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 7.000000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 7.000000f, scale * 7.000000f);
                cui_path_line_to(&path, scale * 10.000000f, scale * 7.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 11.000000f, scale * 6.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 10.000000f, scale * 5.000000f);
                cui_path_line_to(&path, scale * 7.000000f, scale * 5.000000f);
                cui_path_line_to(&path, scale * 7.000000f, scale * 2.000000f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, false, scale * 6.000000f, scale * 1.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, ctx->temporary_memory);

                _cui_path_to_edge_list(path, &edge_list);
                _cui_edge_list_fill(ctx->temporary_memory, &bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;
        }

        _cui_glyph_cache_put(ctx->glyph_cache, 0, shape_type, scale, offset_x, offset_y, uv);

        cui_end_temporary_memory(temp_memory);
    }

    CuiRect rect;
    rect.min.x = (int32_t) bitmap_x;
    rect.min.y = (int32_t) bitmap_y;
    rect.max.x = rect.min.x + cui_rect_get_width(uv);
    rect.max.y = rect.min.y + cui_rect_get_height(uv);

    if (cui_rect_overlap(ctx->clip_rect, rect))
    {
        _cui_push_textured_rect(ctx->command_buffer, rect, uv, color, ctx->glyph_cache->texture_id, ctx->clip_rect_offset);
    }
}
