// DO NOT EDIT. This file is generated by shape_compile.

void
cui_draw_fill_shape(CuiArena *temporary_memory, CuiGraphicsContext *ctx, float x, float y,
                    CuiShapeType shape_type, float scale, CuiColor color)
{
    float draw_x = x;
    float draw_y = y;

    float bitmap_x = floorf(draw_x);
    float bitmap_y = floorf(draw_y);

    float offset_x = draw_x - bitmap_x;
    float offset_y = bitmap_y - draw_y;

    offset_x = 0.125f * roundf(offset_x * 8.0f);
    offset_y = 0.125f * roundf(offset_y * 8.0f);

    CuiRect uv;

    if (!cui_glyph_cache_find(ctx->cache, 0, shape_type, scale, offset_x, offset_y, &uv))
    {
        CuiTemporaryMemory temp_memory = cui_begin_temporary_memory(temporary_memory);

        switch (shape_type)
        {
            case CUI_SHAPE_CHECKBOX_OUTER_16:
            {
                int32_t width  = (int32_t) ceilf(scale * 16.0f);
                int32_t height = (int32_t) ceilf(scale * 16.0f);

                uv = cui_glyph_cache_allocate_texture(ctx->cache, width, height);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, temporary_memory);

                cui_path_move_to(&path, scale * 3.000000f, scale * 15.000000f);
                cui_path_line_to(&path, scale * 13.000000f, scale * 15.000000f);
                cui_path_cubic_curve_to(&path, scale * 14.108001f, scale * 15.000000f, scale * 15.000000f, scale * 14.108000f, scale * 15.000000f, scale * 13.000000f);
                cui_path_line_to(&path, scale * 15.000000f, scale * 3.000000f);
                cui_path_cubic_curve_to(&path, scale * 15.000000f, scale * 1.891999f, scale * 14.108001f, scale * 1.000000f, scale * 13.000000f, scale * 1.000000f);
                cui_path_line_to(&path, scale * 3.000000f, scale * 1.000000f);
                cui_path_cubic_curve_to(&path, scale * 1.892000f, scale * 1.000000f, scale * 1.000000f, scale * 1.891999f, scale * 1.000000f, scale * 3.000000f);
                cui_path_line_to(&path, scale * 1.000000f, scale * 13.000000f);
                cui_path_cubic_curve_to(&path, scale * 1.000000f, scale * 14.108000f, scale * 1.892000f, scale * 15.000000f, scale * 3.000000f, scale * 15.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, temporary_memory);

                cui_path_to_edge_list(path, &edge_list);
                cui_edge_list_fill(&bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_CHECKBOX_INNER_16:
            {
                int32_t width  = (int32_t) ceilf(scale * 16.0f);
                int32_t height = (int32_t) ceilf(scale * 16.0f);

                uv = cui_glyph_cache_allocate_texture(ctx->cache, width, height);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, temporary_memory);

                cui_path_move_to(&path, scale * 3.000000f, scale * 14.000000f);
                cui_path_line_to(&path, scale * 13.000000f, scale * 14.000000f);
                cui_path_cubic_curve_to(&path, scale * 13.554000f, scale * 14.000000f, scale * 14.000000f, scale * 13.554000f, scale * 14.000000f, scale * 13.000000f);
                cui_path_line_to(&path, scale * 14.000000f, scale * 3.000000f);
                cui_path_cubic_curve_to(&path, scale * 14.000000f, scale * 2.446000f, scale * 13.554000f, scale * 2.000000f, scale * 13.000000f, scale * 2.000000f);
                cui_path_line_to(&path, scale * 3.000000f, scale * 2.000000f);
                cui_path_cubic_curve_to(&path, scale * 2.446000f, scale * 2.000000f, scale * 2.000000f, scale * 2.446000f, scale * 2.000000f, scale * 3.000000f);
                cui_path_line_to(&path, scale * 2.000000f, scale * 13.000000f);
                cui_path_cubic_curve_to(&path, scale * 2.000000f, scale * 13.554000f, scale * 2.446000f, scale * 14.000000f, scale * 3.000000f, scale * 14.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, temporary_memory);

                cui_path_to_edge_list(path, &edge_list);
                cui_edge_list_fill(&bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_CHECKMARK_16:
            {
                int32_t width  = (int32_t) ceilf(scale * 16.0f);
                int32_t height = (int32_t) ceilf(scale * 16.0f);

                uv = cui_glyph_cache_allocate_texture(ctx->cache, width, height);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, temporary_memory);

                cui_path_move_to(&path, scale * 11.910155f, scale * 11.996094f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 11.232421f, scale * 11.640625f);
                cui_path_line_to(&path, scale * 6.933594f, scale * 6.480470f);
                cui_path_line_to(&path, scale * 4.707031f, scale * 8.707031f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 3.292969f, scale * 8.707031f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 3.292969f, scale * 7.292970f);
                cui_path_line_to(&path, scale * 6.292968f, scale * 4.292970f);
                cui_path_arc_to(&path, scale * 1.000100f, scale * 1.000100f, 0.000000f, false, true, scale * 7.767578f, scale * 4.359375f);
                cui_path_line_to(&path, scale * 12.767577f, scale * 10.359375f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 12.640625f, scale * 11.767578f);
                cui_path_arc_to(&path, scale * 1.000000f, scale * 1.000000f, 0.000000f, false, true, scale * 11.910155f, scale * 11.996094f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, temporary_memory);

                cui_path_to_edge_list(path, &edge_list);
                cui_edge_list_fill(&bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_LOAD_24:
            {
                int32_t width  = (int32_t) ceilf(scale * 24.0f);
                int32_t height = (int32_t) ceilf(scale * 24.0f);

                uv = cui_glyph_cache_allocate_texture(ctx->cache, width, height);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, temporary_memory);

                cui_path_move_to(&path, scale * 11.921875f, scale * 19.494141f);
                cui_path_arc_to(&path, scale * 0.500050f, scale * 0.500050f, 0.000000f, false, true, scale * 11.646483f, scale * 19.353516f);
                cui_path_line_to(&path, scale * 8.646483f, scale * 16.353516f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 8.646483f, scale * 15.646484f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 9.353516f, scale * 15.646484f);
                cui_path_line_to(&path, scale * 11.500000f, scale * 17.792969f);
                cui_path_line_to(&path, scale * 11.500000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 12.500000f, scale * 10.000000f);
                cui_path_line_to(&path, scale * 12.500000f, scale * 17.792969f);
                cui_path_line_to(&path, scale * 14.646483f, scale * 15.646484f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 15.353516f, scale * 15.646484f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 15.353516f, scale * 16.353516f);
                cui_path_line_to(&path, scale * 12.353516f, scale * 19.353516f);
                cui_path_arc_to(&path, scale * 0.500050f, scale * 0.500050f, 0.000000f, false, true, scale * 11.921875f, scale * 19.494141f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 4.000000f, scale * 12.000000f);
                cui_path_cubic_curve_to(&path, scale * 3.446000f, scale * 12.000000f, scale * 3.000000f, scale * 11.554001f, scale * 3.000000f, scale * 11.000000f);
                cui_path_line_to(&path, scale * 3.000000f, scale * 8.000000f);
                cui_path_cubic_curve_to(&path, scale * 3.000000f, scale * 7.446001f, scale * 3.446000f, scale * 7.000000f, scale * 4.000000f, scale * 7.000000f);
                cui_path_line_to(&path, scale * 20.000000f, scale * 7.000000f);
                cui_path_cubic_curve_to(&path, scale * 20.553999f, scale * 7.000000f, scale * 21.000000f, scale * 7.446001f, scale * 21.000000f, scale * 8.000000f);
                cui_path_line_to(&path, scale * 21.000000f, scale * 11.000000f);
                cui_path_cubic_curve_to(&path, scale * 21.000000f, scale * 11.554001f, scale * 20.553999f, scale * 12.000000f, scale * 20.000000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 14.000000f, scale * 12.000000f);
                cui_path_line_to(&path, scale * 14.000000f, scale * 11.000000f);
                cui_path_line_to(&path, scale * 20.000000f, scale * 11.000000f);
                cui_path_line_to(&path, scale * 20.000000f, scale * 8.000000f);
                cui_path_line_to(&path, scale * 4.000000f, scale * 8.000000f);
                cui_path_line_to(&path, scale * 4.000000f, scale * 11.000000f);
                cui_path_line_to(&path, scale * 10.000000f, scale * 11.000000f);
                cui_path_line_to(&path, scale * 10.000000f, scale * 12.000000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 16.500000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 16.000000f, scale * 9.500000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 16.500000f, scale * 9.000000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 17.000000f, scale * 9.500000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 16.500000f, scale * 10.000000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 18.500000f, scale * 10.000000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 18.000000f, scale * 9.500000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 18.500000f, scale * 9.000000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 19.000000f, scale * 9.500000f);
                cui_path_arc_to(&path, scale * 0.500000f, scale * 0.500000f, 0.000000f, false, true, scale * 18.500000f, scale * 10.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, temporary_memory);

                cui_path_to_edge_list(path, &edge_list);
                cui_edge_list_fill(&bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

            case CUI_SHAPE_TAPE_24:
            {
                int32_t width  = (int32_t) ceilf(scale * 24.0f);
                int32_t height = (int32_t) ceilf(scale * 24.0f);

                uv = cui_glyph_cache_allocate_texture(ctx->cache, width, height);

                CuiBitmap bitmap;
                bitmap.width = cui_rect_get_width(uv);
                bitmap.height = cui_rect_get_height(uv);
                bitmap.stride = ctx->cache->texture.stride;
                bitmap.pixels = (uint8_t *) ctx->cache->texture.pixels + (uv.min.y * bitmap.stride) + (uv.min.x * 4);

                CuiPathCommand *path = 0;
                cui_array_init(path, 16, temporary_memory);

                cui_path_move_to(&path, scale * 6.000000f, scale * 16.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 2.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 6.000000f, scale * 8.000000f);
                cui_path_line_to(&path, scale * 18.000000f, scale * 8.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 22.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 18.000000f, scale * 16.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 14.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 15.357422f, scale * 9.000000f);
                cui_path_line_to(&path, scale * 8.642577f, scale * 9.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 10.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 4.000000f, scale * 4.000000f, 0.000000f, false, true, scale * 6.000000f, scale * 16.000000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 6.000000f, scale * 15.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 9.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 6.000000f, scale * 9.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 3.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 6.000000f, scale * 15.000000f);
                cui_path_close(&path);
                cui_path_move_to(&path, scale * 18.000000f, scale * 15.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 21.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 18.000000f, scale * 9.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 15.000000f, scale * 12.000000f);
                cui_path_arc_to(&path, scale * 3.000000f, scale * 3.000000f, 0.000000f, false, false, scale * 18.000000f, scale * 15.000000f);
                cui_path_close(&path);

                CuiEdge *edge_list = 0;
                cui_array_init(edge_list, 16, temporary_memory);

                cui_path_to_edge_list(path, &edge_list);
                cui_edge_list_fill(&bitmap, edge_list, cui_make_color(1.0f, 1.0f, 1.0f, 1.0f));
            } break;

        }

        cui_glyph_cache_put(ctx->cache, 0, shape_type, scale, offset_x, offset_y, uv);

        cui_end_temporary_memory(temp_memory);
    }

    CuiRect rect;
    rect.min.x = (int32_t) bitmap_x;
    rect.min.y = (int32_t) bitmap_y;
    rect.max.x = rect.min.x + cui_rect_get_width(uv);
    rect.max.y = rect.min.y + cui_rect_get_height(uv);

    // TODO: if overlap

    cui_draw_fill_textured_rect(ctx, rect, uv, color);
}
